version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      rebase-strategy: "auto"
      open-pull-requests-limit: 3
      groups:
          minor-and-patch:
               update-types:
                   - "minor"
                   - "patch"
