title: Weglot Design Styleguide
description: >- # this means to ignore newlines until "baseurl:"
  This is the Weglot Design styleguide.
baseurl: "/design" # the subpath of your site, e.g. /blog
url: "https://weglot.github.io"
twitter_username: weglot
github_username:  weglot

destination: ../docs

sass:
  sass_dir: _sass
  style: :compressed

collections:
  foundations:
    output: false
  components:
    output: false

