title: Weglot Design Styleguide
description: >-
  This is the Weglot Design styleguide.
baseurl: "/design" # the subpath of your site, e.g. /blog
url: "https://weglot.github.io"
twitter_username: weglot
github_username:  weglot

destination: ../docs

sass:
  sass_dir: _sass
  style: :compressed

collections:
  docs:
    output: true


defaults:
  - scope:
      path: "_docs/foundations"
    values:
      type: foundation
      layout: doc
  - scope:
      path: "_docs/components"
    values:
      type: component
      layout: doc