name: Checks

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version-file: ".nvmrc"
                  registry-url: https://npm.pkg.github.com/
                  scope: "@weglot"
            - run: npm install
            - run: npm run stylelint:ci
            - run: npm run build
