name: Deploy Jekyll site to Pages

on:
    push:
        tags:
            - '*'

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version:
                    - master
                    - 2.6.3

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ matrix.version == 'master' && 'master' || matrix.version }}

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  working-directory: ./styleguide
                  ruby-version: '3.1'
                  bundler-cache: true

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v5

            - run: npm install

            - run: npm run build docs/${{ matrix.version }}

            - name: Build with Jekyll
              run: |
                  if [ "${{ matrix.version }}" == "master" ]; then
                    bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --destination ../docs
                  else
                    bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}/${{ matrix.version }}" --destination ../docs/${{ matrix.version }}
                  fi
              working-directory: ./styleguide
              env:
                  JEKYLL_ENV: production

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  name: ${{ matrix.version }}
                  path: docs/

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Merge Artifacts
              uses: actions/upload-artifact/merge@v4
              with:
                  name: github-pages

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
